remove versioning dependency

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,45 +6,45 @@ on:
       - '**'
 
 jobs:
-  versioning:
-    runs-on: ubuntu-latest
-    outputs:
-          tag: ${{ steps.versioning.outputs.tag }}
-    steps:
-      # Checkout the repository
-      - name: Checkout code
-        uses: actions/checkout@v3
-      # Determine the latest merged branch
-      - name: Get Merged Branch
-        id: latest_merged_branch
-        run: |
-          MERGED_BRANCH=${{ github.head_ref }}
-          echo "MERGED_BRANCH=${MERGED_BRANCH}" >> $GITHUB_ENV
-      # Determine the version based on the latest tag and branch name
-      - name: Determing Version
-        id: versioning
-        run: |
-          git fetch --tags
-          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
-          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
+  # versioning:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #         tag: ${{ steps.versioning.outputs.tag }}
+  #   steps:
+  #     # Checkout the repository
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
+  #     # Determine the latest merged branch
+  #     - name: Get Merged Branch
+  #       id: latest_merged_branch
+  #       run: |
+  #         MERGED_BRANCH=${{ github.head_ref }}
+  #         echo "MERGED_BRANCH=${MERGED_BRANCH}" >> $GITHUB_ENV
+  #     # Determine the version based on the latest tag and branch name
+  #     - name: Determing Version
+  #       id: versioning
+  #       run: |
+  #         git fetch --tags
+  #         LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
+  #         IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
 
-          BRANCH_NAME=$(echo "${{ env.MERGED_BRANCH }}")
+  #         BRANCH_NAME=$(echo "${{ env.MERGED_BRANCH }}")
 
-          if [[ "$BRANCH_NAME" == *feature* ]]; then
-            MINOR=$((MINOR + 1))
-            PATCH=0
-          elif [[ "$BRANCH_NAME" == *bugfix* ]]; then
-            PATCH=$((PATCH + 2))
-          else
-            echo "Error: Unsupported branch name '$BRANCH_NAME'. Expected to contain 'feature' or 'bugfix', current name: '$BRANCH_NAME'."
-            exit 1
-          fi
+  #         if [[ "$BRANCH_NAME" == *feature* ]]; then
+  #           MINOR=$((MINOR + 1))
+  #           PATCH=0
+  #         elif [[ "$BRANCH_NAME" == *bugfix* ]]; then
+  #           PATCH=$((PATCH + 2))
+  #         else
+  #           echo "Error: Unsupported branch name '$BRANCH_NAME'. Expected to contain 'feature' or 'bugfix', current name: '$BRANCH_NAME'."
+  #           exit 1
+  #         fi
 
-          NEW_TAG="$MAJOR.$MINOR.$PATCH"
+  #         NEW_TAG="$MAJOR.$MINOR.$PATCH"
 
-          echo "tag=${NEW_TAG}" >> $GITHUB_OUTPUT
+  #         echo "tag=${NEW_TAG}" >> $GITHUB_OUTPUT
   build:
-    needs: versioning
+    # needs: versioning
     runs-on: ubuntu-latest
 
     steps:
